### PR TITLE
Implemented playback speed on iOS

### PR DESCRIPTION
**Pull request by recastrodiaz**
Hi @JONA-Cureambit,

I've implemented the playback speed on iOS based on your latest commits. 

By accepting this PR, the iOS implementation should automatically be available in https://github.com/flutter/plugins/pull/1400

Let me know if you are OK to merge this or if you have any questions. Tested on an iPhone XR and an iPhone 4s.

PS: You need to rebase your master branch against the upstream origin so GH can display the correct diff/changes.

### CODE REVIEW

**Comment by JONA-Cureambit** [comment]
Hi @recastrodiaz,

I have accepted your PR in my repo and rebase my master against the upstream. After making these changes in my master i am seeing many others commit as well. I am novice to github and this is my first contribution to open source.

Please verify this from your end and let me know if any changes need to be done.

**Comment by recastrodiaz** [comment]
Hi @JONA-Cureambit 

Can you try the following:

```SH
git checkout master              # switch to your local master branch if not already don
git fetch upstream                # retrieve all commits from flutter/plugins
git merge upstream/master # merge flutter/master with your local master branch
```

**Comment by JONA-Cureambit** [comment]
Already all changes up to date.

I am wondering why others commits are also there in my PR after rebase and merge

**Comment by recastrodiaz** [comment]
I would suggest you start from scratch:

1. Create a new branch from upstream/master and 
2. cherry-pick all of your commits and my iOS commit. 
3. Then replace your master branch with this new branch and force push to GitHub.

**Comment by JONA-Cureambit** [comment]
Hi @recastrodiaz ,

I followed above all step but still seeing same issue in flutter#1400

**Comment by love-bk** [comment]
I tested it with the ios real machine version 12.4.1, setting speed no matter what.

**Pull request merged**
